spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
    discovery:
      enabled: true
    gateway:
      server:
        routes:
          - id: r1
            uri: lb://CUSTOMER-SERVICE
            predicates:
              - Path=/api/customers/**
          - id: r2
            uri: lb://INVENTORY-SERVICE
            predicates:
              - Path=/api/products/**

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true